# site settings

title: Marielena Soilemezidi
description: PhD candidate at NKUA & RA at UiO
taglong: Personal Website of Marielena Soilemezidi
tagshort: Personal Website
url: https://marielena-soilemezidi.netlify.app
baseurl: ""
permalink: msoil
repo: https://github.com/marielenas.github.io/

# author settings

author:
  name: Marielena Soilemezidi
  email: soilemezidi.m.e@gmail.com
photo: /assets/Soilemezidi_Medit2.jpg

# social media links

social:
  github: MarielenaS
  instagram: soilemezidi.m.e
  linkedin: marielena-soilemezidi

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
